# Generated by Django 5.0.4 on 2024-04-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
    ]
