# Generated by Django 5.0.4 on 2024-04-30 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0003_categoryvehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('periodicite', models.CharField(choices=[('Journalier', 'Journalier'), ('Hebdomadaire', 'Hebdomadaire'), ('Mensuel', 'Mensuel'), ('Annuelle', 'Annuelle')], max_length=12)),
                ('category_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoHeavenWebsite.categoryvehicule')),
            ],
        ),
    ]
