# Generated by Django 5.0.4 on 2024-05-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0007_alter_vehicule_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='model',
            field=models.CharField(max_length=15),
        ),
    ]
