# Generated by Django 5.0.4 on 2024-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0009_alter_tarif_uniq_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='uniq_tarif',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
