# Generated by Django 5.0.4 on 2024-05-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0010_alter_tarif_uniq_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoHeavenWebsite.tarif'),
        ),
      
    ]
