# Generated by Django 5.0.4 on 2024-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0011_location_tarif_tarifvehiculeliaison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='tarif_ids',
            field=models.ManyToManyField(to='AutoHeavenWebsite.tarif', verbose_name='Liste des tarifs'),
        ),
    ]
