# Generated by Django 5.0.4 on 2024-05-12 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHeavenWebsite', '0012_vehicule_tarif_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='proprio_vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employé', 'Employé'), ('Client', 'Client'), ('Proprio', 'Proprio'), ('SuperAdmin', 'SuperAdmin')], max_length=10),
        ),
    ]
